# Generated by Django 4.1.13 on 2025-09-30 02:58

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regisacc',
            name='user_image',
            field=models.ImageField(default='profile/image.png', upload_to=user.models.image_path),
        ),
    ]
