# Generated by Django 4.1.13 on 2025-09-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_regisacc_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='regisacc',
            name='randomstrings',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
